lights:
  description: "An array of light in the home."
  type: "array"
  required: true
  items:
    type: "object"
    required: true
    properties:
      name:
        type: "string"
        required: true
      mac:
        type: "string"
        pattern: "^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"
        required: true
      ip:
        type: "string"
        pattern: "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$"
        required: true
rooms:
  description: "An array of rooms with their respective lights in the home."
  type: "array"
  required: true
  items:
    type: "object"
    required: true
    properties:
      name:
        type: "string"
        required: true
      lights:
        type: "array"
        required: true
        items:
          type: "string"
          required: true

