---
name: sunrise_trigger
pack: lifx
description: Sets the daylight scene at sunrise in all but the bedroom.
enabled: true
trigger:
  type: astral.sunrise
  ref: astral.sunrise
  description: Trigger type for sunrise.
action:
  ref: lifx.set_daylight
  description: Sets the daylight scene at sunrise in all but the bedroom.